server:
  port: 8080
spring.datasource:
    driverClassName: com.mysql.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/knox_db
    url: jdbc:mysql://host.docker.internal:3306/knox_db
    username: root
    password: Passw0rd1
    platform: mysql
    jpa:
      database-platform: org.hibernate.dialect.MySQL5Dialect
      spring.jpa.hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      hibernate.ddl-auto: none

      generate-ddl: true
      show-sql: true


app.auth:
  user:
    userName: test
    authorizationHash: bab26aeff98b59ff1db77a5240d7f400c10cdae0
  users[0]:
    userName: ws02
    authorizationHash: bab26aeff98b59ff1db77a5240d7f400c10cdae0
  users[1]:
    userName: devutils
    authorizationHash: cbf1c1892f393111c4cb043f6c285670249526fd
  users[2]:
    userName: local
    authorizationHash: 12ff9874235f510de1ade0621662ac7fb84b43d1



app:
  otpGateWayUrl: https://api.bulksms.com/v1/messages
  otpGateWayId: 447D41A906584B8981BD19F7CE185D41-01-3
  otpGateWaySecret: E0pOPSiNGp!y4QkKiSUoLE*e#uCly
  otpValidity: 15
  mobileRechargeApiUserName: aatadmintest3
  mobileRechargeApiPassword: 2W874sAFwN
  topupDebug: true
  secretKey: Y1cR4$P8[6,Nr61
  smtpEnabled: true
  smtpUser: AKIAR25TUUKOHMSJDEKW
  smtpPassword: BFyox+ap3d6ezMt+r9tc6CHZd5zgP3QslG7iCeiPUS5c
  smtpServer: email-smtp.us-east-2.amazonaws.com
  smtpFromEmailAddress: llanterme@gmail.com




